{"name": "Check if website do not allow the user to login with incorrect credential", "status": "failed", "statusDetails": {"message": "AssertionError: find your account is not in Your account is locked. Please click on forgot password link to reset.\n", "trace": "  File \"/Users/mary/opt/anaconda3/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/mary/opt/anaconda3/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/sign_in_steps.py\", line 44, in verify_user_is_not_logged_in\n    context.app.sign_in_page.verify_user_is_not_logged_in()\n  File \"/Users/mary/Documents/QA Course/Careerist/Python and QA Automation/QA Automation/python-selenium-automation/pages/sign_in_page.py\", line 31, in verify_user_is_not_logged_in\n    self.verify_partial_text(self.NOT_LOGED_IN_TXT,\"find your account\" )\n  File \"/Users/mary/Documents/QA Course/Careerist/Python and QA Automation/QA Automation/python-selenium-automation/pages/base_page.py\", line 79, in verify_partial_text\n    assert expected_text in actual_text, f\"{expected_text} is not in {actual_text}\"\n"}, "steps": [{"name": "Given Open target main page", "status": "passed", "start": 1725835089474, "stop": 1725835094320}, {"name": "When Click Sign In", "status": "passed", "start": 1725835094320, "stop": 1725835094445}, {"name": "When From right side navigation menu, click Sign In", "status": "passed", "start": 1725835094445, "stop": 1725835095241}, {"name": "Then Verify Sign In form opened", "status": "passed", "start": 1725835095242, "stop": 1725835096026}, {"name": "When Input test@gmail.com and Test123433332 on SignIn page", "status": "passed", "start": 1725835096026, "stop": 1725835096379}, {"name": "When Click Sign In with password", "status": "passed", "start": 1725835096379, "stop": 1725835096471}, {"name": "Then Verifies that “We can't find your account.” message is shown", "status": "failed", "statusDetails": {"message": "AssertionError: find your account is not in Your account is locked. Please click on forgot password link to reset.\n", "trace": "  File \"/Users/mary/opt/anaconda3/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/mary/opt/anaconda3/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/sign_in_steps.py\", line 44, in verify_user_is_not_logged_in\n    context.app.sign_in_page.verify_user_is_not_logged_in()\n  File \"/Users/mary/Documents/QA Course/Careerist/Python and QA Automation/QA Automation/python-selenium-automation/pages/sign_in_page.py\", line 31, in verify_user_is_not_logged_in\n    self.verify_partial_text(self.NOT_LOGED_IN_TXT,\"find your account\" )\n  File \"/Users/mary/Documents/QA Course/Careerist/Python and QA Automation/QA Automation/python-selenium-automation/pages/base_page.py\", line 79, in verify_partial_text\n    assert expected_text in actual_text, f\"{expected_text} is not in {actual_text}\"\n"}, "start": 1725835096471, "stop": 1725835096830}], "start": 1725835087154, "stop": 1725835097023, "uuid": "c09b8146-6c64-44c7-b6b3-66ebfd7a253d", "historyId": "9eb078f76fea7d2b2dcf950b6f8ca54f", "fullName": "test caces for the sign in page: Check if website do not allow the user to login with incorrect credential", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "smoke"}, {"name": "feature", "value": "test caces for the sign in page"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}